# Generated by Django 3.1.7 on 2021-02-26 23:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'مهارت کدزنی',
                'verbose_name_plural': 'مهارت کدزنی',
            },
        ),
        migrations.CreateModel(
            name='DesignSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'مهارت طراحی',
                'verbose_name_plural': 'مهارت طراحی',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('where', models.CharField(max_length=50)),
                ('what', models.CharField(max_length=50)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=200)),
            ],
            options={
                'verbose_name': 'تحصیل',
                'verbose_name_plural': 'تحصیلات',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('where', models.CharField(max_length=50)),
                ('what', models.CharField(max_length=50)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=200)),
            ],
            options={
                'verbose_name': 'تجربه',
                'verbose_name_plural': 'تجربیات',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'دانش',
                'verbose_name_plural': 'دانش',
            },
        ),
    ]
