# Generated by Django 3.1.7 on 2021-02-23 21:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='About_me',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='doing',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
