# Generated by Django 3.1.7 on 2021-02-23 22:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_doing2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doing',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doing2',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=200),
        ),
    ]
