# Generated by Django 3.1.7 on 2021-02-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='map_embeded',
            field=models.CharField(max_length=600),
        ),
    ]
