# Generated by Django 3.1.7 on 2021-02-26 23:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_me', ckeditor_uploader.fields.RichTextUploadingField()),
                ('age', models.CharField(max_length=5)),
                ('residence', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'درباره من',
                'verbose_name_plural': 'درباره من',
            },
        ),
        migrations.CreateModel(
            name='Doing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=200)),
            ],
            options={
                'verbose_name': 'کار های من',
                'verbose_name_plural': 'کار های من',
            },
        ),
        migrations.CreateModel(
            name='Doing2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=200)),
            ],
            options={
                'verbose_name': 'کار های من',
                'verbose_name_plural': 'کار های من',
            },
        ),
    ]
