# Generated by Django 3.1.7 on 2021-02-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210224_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostManager',
        ),
    ]
