# Generated by Django 3.1.7 on 2021-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_auto_20210223_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='site_address',
            field=models.URLField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='site_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
