# Generated by Django 3.1.7 on 2021-02-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('site_address', models.URLField(max_length=150, null=True)),
                ('site_title', models.CharField(max_length=150, null=True)),
                ('job', models.CharField(max_length=150)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('git', models.URLField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='files/')),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه اول',
                'verbose_name_plural': 'اطلاعات صفحه اول',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'کار ها',
            },
        ),
    ]
